import React, { Component } from 'react';
import { View, StyleSheet, Text, FlatList, Alert } from 'react-native';

import { PilotItem } from '../../components';
import { config } from './config';
import styles from './styles';

import { getIconSizePixelRatio, switchIconPerPlatform } from '../../utils';

import Ionicons from 'react-native-vector-icons/Ionicons';

const VIEWABILITY_CONFIG = {
  minimumViewTime: 3000,
  viewAreaCoveragePercentThreshold: 100,
  waitForInteraction: true,
};

class Pilots extends Component {
  constructor(props) {
    super(props);

    this.props.navigator.setTitle({
      title: 'Pilots',
    });
  }

  static navigatorStyle = {
    ...config.navigatorStyles,
  };

  static navigatorButtons = {
    ...config.navigatorButtons,
  };

  state = {
    items: [
      {
        city: 'belmont',
        primary_balloons: [
          {
            year_manufactured: '1996',
            reg_num: 'C-FYEE',
            balloon_size_unit: 'cubic feet',
            shape_balloon: 'No',
            photos_url: 'https://registration.balloonfiesta.com/hotair/balloon/image/C-FYEE',
            balloon_name: 'Sundance Balloons',
            logo: 'Yes',
            balloon_design_desc: 'Multi coloured vertical stripes with Sundance Balloons logo in middle',
            model: 'A250',
            manufacturer: 'Cameron',
            key: 670,
            balloon_size: '250000',
          },
        ],
        country: 'CA',
        key: 651,
        additional_balloons: [],
        state: 'ontario',
        common_name: 'Abraham Folque',
        events: [
          {
            competition_balloon_id: null,
            banner_number: '610',
            launch_thur_fri: '',
            launch_shapes: '',
            launch_9day: 'N3',
            launch_balloon_glow: '',
            aloft: 'No',
            launch_twilight_twinkle: '',
            launch_rodeo: 'N3',
            program_balloon_id: 670,
            aloft_school: '',
            launch_night_magic: '',
            us_national_competition: 'No',
          },
        ],
      },
      {
        city: 'Canton',
        primary_balloons: [],
        country: 'US',
        key: 751,
        additional_balloons: [
          {
            year_manufactured: '2006',
            reg_num: 'N898LB',
            balloon_size_unit: 'cubic feet',
            shape_balloon: 'No',
            photos_url: 'https://registration.balloonfiesta.com/hotair/balloon/image/N898LB',
            balloon_name: 'Never Too Old',
            logo: 'No',
            balloon_design_desc: 'Blue(3 shades), \r\nGreen(3 shades), \r\nPurple, Yellow\r\nZig-Zag patern',
            model: '90A',
            manufacturer: 'Lindstrand',
            key: 158,
            balloon_size: '90000',
          },
        ],
        state: 'MA',
        common_name: 'Adam Williams',
        events: null,
      },
      {
        city: 'Lachen',
        primary_balloons: [
          {
            year_manufactured: '2015',
            reg_num: 'HB-QZC',
            balloon_size_unit: 'cubic meters',
            shape_balloon: 'No',
            photos_url: 'https://registration.balloonfiesta.com/hotair/balloon/image/HB-QZC',
            balloon_name: "Cupid's Heart",
            logo: 'No',
            balloon_design_desc: 'red heart on silver with golden cupid',
            model: 'G-90',
            manufacturer: 'Ultra Magic',
            key: 542,
            balloon_size: '2550',
          },
        ],
        country: 'CH',
        key: 523,
        additional_balloons: [],
        state: 'ZH',
        common_name: 'Adrian Held',
        events: [
          {
            competition_balloon_id: 542,
            banner_number: '231',
            launch_thur_fri: '',
            launch_shapes: '',
            launch_9day: 'J10',
            launch_balloon_glow: '',
            aloft: 'No',
            launch_twilight_twinkle: 'J5',
            launch_rodeo: '',
            program_balloon_id: 542,
            aloft_school: '',
            launch_night_magic: '',
            us_national_competition: 'No',
          },
        ],
      },
      {
        city: 'Grass Lake',
        primary_balloons: [],
        country: 'US',
        key: 315,
        additional_balloons: [
          {
            year_manufactured: '2015',
            reg_num: 'N590RW',
            balloon_size_unit: 'cubic feet',
            shape_balloon: 'No',
            photos_url: 'https://registration.balloonfiesta.com/hotair/balloon/image/N590RW',
            balloon_name: 'New-but-sold',
            logo: 'No',
            balloon_design_desc: 'Rainbow equator with black and white top and bottom',
            model: 'V-90',
            manufacturer: 'Cameron',
            key: 233,
            balloon_size: '90000',
          },
        ],
        state: 'MI',
        common_name: 'Al Smith',
        events: null,
      },
      {
        city: 'Ottawa',
        primary_balloons: [
          {
            year_manufactured: '2015',
            reg_num: 'C-FIIY',
            balloon_size_unit: 'cubic feet',
            shape_balloon: 'Yes',
            photos_url: 'https://registration.balloonfiesta.com/hotair/balloon/image/C-FIIY',
            balloon_name: 'Alien Rocket',
            logo: 'No',
            balloon_design_desc: 'Alien Rocket, Black and Green',
            model: 'Alien Rocket',
            manufacturer: 'Home Built',
            key: 548,
            balloon_size: '70000',
          },
        ],
        country: 'CA',
        key: 530,
        additional_balloons: [],
        state: 'ON',
        common_name: 'Alain Bard',
        events: [
          {
            competition_balloon_id: null,
            banner_number: '508',
            launch_thur_fri: 'K5',
            launch_shapes: 'P4',
            launch_9day: '',
            launch_balloon_glow: '',
            aloft: 'No',
            launch_twilight_twinkle: 'N2',
            launch_rodeo: 'K3',
            program_balloon_id: 548,
            aloft_school: '',
            launch_night_magic: '',
            us_national_competition: 'No',
          },
        ],
      },
      {
        city: 'Albuquerque',
        primary_balloons: [
          {
            year_manufactured: '2006',
            reg_num: 'N87SB',
            balloon_size_unit: 'cubic feet',
            shape_balloon: 'Yes',
            photos_url: 'https://registration.balloonfiesta.com/hotair/balloon/image/N87SB',
            balloon_name: 'Smokey Bear',
            logo: 'Yes',
            balloon_design_desc: 'Brown, with Ranger hat',
            model: 'SP-1',
            manufacturer: 'Aerostar',
            key: 338,
            balloon_size: '145000',
          },
        ],
        country: 'US',
        key: 333,
        additional_balloons: [],
        state: 'NM',
        common_name: 'Alan Wynn',
        events: [
          {
            competition_balloon_id: null,
            banner_number: '444',
            launch_thur_fri: 'F4',
            launch_shapes: 'U10',
            launch_9day: '',
            launch_balloon_glow: '',
            aloft: 'No',
            launch_twilight_twinkle: '',
            launch_rodeo: 'F3',
            program_balloon_id: 338,
            aloft_school: '',
            launch_night_magic: '',
            us_national_competition: 'No',
          },
        ],
      },
      {
        city: 'Niles',
        primary_balloons: [
          {
            year_manufactured: '1997',
            reg_num: 'N830AL',
            balloon_size_unit: 'cubic feet',
            shape_balloon: 'No',
            photos_url: 'https://registration.balloonfiesta.com/hotair/balloon/image/N830AL',
            balloon_name: 'Featherlight II',
            logo: 'No',
            balloon_design_desc: 'Spectrum with Every Third Gore White',
            model: 'Firefly',
            manufacturer: 'Balloon Works',
            key: 626,
            balloon_size: '77500',
          },
        ],
        country: 'US',
        key: 611,
        additional_balloons: [],
        state: 'IL',
        common_name: 'Alan Zielinski',
        events: [
          {
            competition_balloon_id: null,
            banner_number: '538',
            launch_thur_fri: '',
            launch_shapes: '',
            launch_9day: 'G7',
            launch_balloon_glow: 'B7',
            aloft: 'No',
            launch_twilight_twinkle: '',
            launch_rodeo: 'G7',
            program_balloon_id: 626,
            aloft_school: '',
            launch_night_magic: 'F5',
            us_national_competition: 'No',
          },
        ],
      },
      {
        city: 'Albuquerque',
        primary_balloons: [
          {
            year_manufactured: '2008',
            reg_num: 'N800SR',
            balloon_size_unit: 'cubic feet',
            shape_balloon: 'No',
            photos_url: 'https://registration.balloonfiesta.com/hotair/balloon/image/N800SR',
            balloon_name: 'SUNSET RISE',
            logo: 'No',
            balloon_design_desc: 'YELLOW SUN SETTING IN MULTI COLOR SUNSET, BLUE SKY ABOVE',
            model: 'AX8-105',
            manufacturer: 'Head',
            key: 18,
            balloon_size: '105000',
          },
        ],
        country: 'US',
        key: 21,
        additional_balloons: [],
        state: 'NM',
        common_name: 'ALBERT LOWENSTEIN',
        events: [
          {
            competition_balloon_id: 18,
            banner_number: '128',
            launch_thur_fri: '',
            launch_shapes: '',
            launch_9day: 'F1',
            launch_balloon_glow: 'F1',
            aloft: 'Yes',
            launch_twilight_twinkle: 'F1',
            launch_rodeo: '',
            program_balloon_id: 18,
            aloft_school: 'Alameda ',
            launch_night_magic: 'F1',
            us_national_competition: 'No',
          },
        ],
      },
      {
        city: 'Lancashire',
        primary_balloons: [
          {
            year_manufactured: '2016',
            reg_num: 'N6102L',
            balloon_size_unit: 'cubic feet',
            shape_balloon: 'No',
            photos_url: 'https://registration.balloonfiesta.com/hotair/balloon/image/N6102L',
            balloon_name: 'Hopper',
            logo: 'No',
            balloon_design_desc: 'Yellow and Blue stripes',
            model: '31A',
            manufacturer: 'Lindstrand',
            key: 558,
            balloon_size: '31000',
          },
        ],
        country: 'GB',
        key: 503,
        additional_balloons: [
          {
            year_manufactured: '2015',
            reg_num: 'G-CIWK',
            balloon_size_unit: 'cubic feet',
            shape_balloon: 'No',
            photos_url: 'https://registration.balloonfiesta.com/hotair/balloon/image/G-CIWK',
            balloon_name: 'Demo',
            logo: 'Yes',
            balloon_design_desc: 'Blue and Yellow',
            model: 'Lindstrand Technologies',
            manufacturer: 'Lindstrand',
            key: 534,
            balloon_size: '105000',
          },
        ],
        state: 'Ormskirk',
        common_name: 'Alex Court',
        events: [
          {
            competition_balloon_id: null,
            banner_number: '596',
            launch_thur_fri: '',
            launch_shapes: '',
            launch_9day: 'Q9',
            launch_balloon_glow: '',
            aloft: 'No',
            launch_twilight_twinkle: 'N6',
            launch_rodeo: '',
            program_balloon_id: 558,
            aloft_school: '',
            launch_night_magic: '',
            us_national_competition: 'No',
          },
        ],
      },
      {
        city: 'Bernalillo',
        primary_balloons: [
          {
            year_manufactured: '2013',
            reg_num: 'N166RR',
            balloon_size_unit: 'cubic feet',
            shape_balloon: 'No',
            photos_url: 'https://registration.balloonfiesta.com/hotair/balloon/image/N166RR',
            balloon_name: 'Rainbow Ryders 160',
            logo: 'No',
            balloon_design_desc: 'Rainbow Ryders',
            model: '160A',
            manufacturer: 'Lindstrand',
            key: 731,
            balloon_size: '160000',
          },
        ],
        country: 'US',
        key: 455,
        additional_balloons: [],
        state: 'NM',
        common_name: 'Alfred Salazar',
        events: [
          {
            competition_balloon_id: null,
            banner_number: '628',
            launch_thur_fri: '',
            launch_shapes: '',
            launch_9day: 'M3',
            launch_balloon_glow: '',
            aloft: 'No',
            launch_twilight_twinkle: '',
            launch_rodeo: 'M3',
            program_balloon_id: 731,
            aloft_school: '',
            launch_night_magic: '',
            us_national_competition: 'No',
          },
        ],
      },
      {
        city: 'Albuquerque',
        primary_balloons: [
          {
            year_manufactured: '1994',
            reg_num: 'N90QQ',
            balloon_size_unit: 'cubic feet',
            shape_balloon: 'No',
            photos_url: 'https://registration.balloonfiesta.com/hotair/balloon/image/N90QQ',
            balloon_name: 'Heaven Bound, too',
            logo: 'No',
            balloon_design_desc: 'Blue, with rainbow banding around the equator.',
            model: 'Viva',
            manufacturer: 'Cameron',
            key: 406,
            balloon_size: '90000',
          },
        ],
        country: 'US',
        key: 392,
        additional_balloons: [],
        state: 'NM',
        common_name: 'Allan Hahn',
        events: [
          {
            competition_balloon_id: 406,
            banner_number: '246',
            launch_thur_fri: '',
            launch_shapes: '',
            launch_9day: 'H11',
            launch_balloon_glow: 'H6',
            aloft: 'Yes',
            launch_twilight_twinkle: '',
            launch_rodeo: 'H11',
            program_balloon_id: 406,
            aloft_school: 'Painted Sky ',
            launch_night_magic: '',
            us_national_competition: 'No',
          },
        ],
      },
      {
        city: 'Minden',
        primary_balloons: [
          {
            year_manufactured: '2013',
            reg_num: 'N777XD',
            balloon_size_unit: 'cubic feet',
            shape_balloon: 'No',
            photos_url: 'https://registration.balloonfiesta.com/hotair/balloon/image/N777XD',
            balloon_name: 'Pixie Dust',
            logo: 'No',
            balloon_design_desc: 'Yellow multi color spiral',
            model: 'O90',
            manufacturer: 'Cameron',
            key: 42,
            balloon_size: '90000',
          },
        ],
        country: 'US',
        key: 38,
        additional_balloons: [],
        state: 'NV',
        common_name: 'Allen Anderson',
        events: [
          {
            competition_balloon_id: 42,
            banner_number: '193',
            launch_thur_fri: '',
            launch_shapes: '',
            launch_9day: 'G2',
            launch_balloon_glow: '',
            aloft: 'No',
            launch_twilight_twinkle: 'G2',
            launch_rodeo: '',
            program_balloon_id: 42,
            aloft_school: '',
            launch_night_magic: 'G2',
            us_national_competition: 'No',
          },
        ],
      },
      {
        city: 'Arlington',
        primary_balloons: [
          {
            year_manufactured: '1994',
            reg_num: 'N1603U',
            balloon_size_unit: 'cubic feet',
            shape_balloon: 'No',
            photos_url: 'https://registration.balloonfiesta.com/hotair/balloon/image/N1603U',
            balloon_name: 'Stardust',
            logo: 'No',
            balloon_design_desc: 'Yellow and Red with Purple on top and bottom',
            model: 'Concept',
            manufacturer: 'Cameron',
            key: 15,
            balloon_size: '80000',
          },
        ],
        country: 'US',
        key: 24,
        additional_balloons: [],
        state: 'TX',
        common_name: 'Amanda Ibbotson',
        events: [
          {
            competition_balloon_id: 15,
            banner_number: '129',
            launch_thur_fri: '',
            launch_shapes: '',
            launch_9day: 'U2',
            launch_balloon_glow: 'U2',
            aloft: 'No',
            launch_twilight_twinkle: 'U2',
            launch_rodeo: '',
            program_balloon_id: 15,
            aloft_school: '',
            launch_night_magic: 'U2',
            us_national_competition: 'No',
          },
        ],
      },
      {
        city: 'Overland Park',
        primary_balloons: [],
        country: 'US',
        key: 265,
        additional_balloons: [
          {
            year_manufactured: '2013',
            reg_num: 'N65397',
            balloon_size_unit: 'cubic feet',
            shape_balloon: 'No',
            photos_url: 'https://registration.balloonfiesta.com/hotair/balloon/image/N65397',
            balloon_name: 'Wonder Bread',
            logo: 'Yes',
            balloon_design_desc: 'White, Red, Yellow, Blue \r\nWith "Wonder" logo',
            model: 'Z90',
            manufacturer: 'Cameron',
            key: 193,
            balloon_size: '90000',
          },
        ],
        state: 'KS',
        common_name: 'Amanda Sabia',
        events: null,
      },
      {
        city: 'Breadstone',
        primary_balloons: [
          {
            year_manufactured: '2015',
            reg_num: 'G-UINZ',
            balloon_size_unit: 'cubic feet',
            shape_balloon: 'Yes',
            photos_url: 'https://registration.balloonfiesta.com/hotair/balloon/image/G-UINZ',
            balloon_name: 'Splash',
            logo: 'No',
            balloon_design_desc: 'Penguin, female with nail varnish on her toes :)',
            model: 'B70 Penguin',
            manufacturer: 'Ultra Magic',
            key: 683,
            balloon_size: '70000',
          },
        ],
        country: 'GB',
        key: 662,
        additional_balloons: [],
        state: 'Berkeley',
        common_name: 'Andrew Holly',
        events: [
          {
            competition_balloon_id: null,
            banner_number: '421',
            launch_thur_fri: 'M2',
            launch_shapes: 'N1',
            launch_9day: '',
            launch_balloon_glow: '',
            aloft: 'No',
            launch_twilight_twinkle: 'M2',
            launch_rodeo: 'M1',
            program_balloon_id: 683,
            aloft_school: '',
            launch_night_magic: '',
            us_national_competition: 'No',
          },
        ],
      },
      {
        city: 'Irchester',
        primary_balloons: [
          {
            year_manufactured: '2002',
            reg_num: 'G-CBMK',
            balloon_size_unit: 'cubic feet',
            shape_balloon: 'No',
            photos_url: 'https://registration.balloonfiesta.com/hotair/balloon/image/G-CBMK',
            balloon_name: 'Rooftops',
            logo: 'No',
            balloon_design_desc: 'Blue with houses around the bottom',
            model: 'Cameron Z-120',
            manufacturer: 'Cameron',
            key: 274,
            balloon_size: '120000',
          },
        ],
        country: 'GB',
        key: 264,
        additional_balloons: [],
        state: 'Northants',
        common_name: 'Andrew Kaye',
        events: [
          {
            competition_balloon_id: null,
            banner_number: '386',
            launch_thur_fri: '',
            launch_shapes: '',
            launch_9day: 'Q6',
            launch_balloon_glow: 'Q5',
            aloft: 'No',
            launch_twilight_twinkle: '',
            launch_rodeo: 'Q6',
            program_balloon_id: 274,
            aloft_school: '',
            launch_night_magic: '',
            us_national_competition: 'No',
          },
        ],
      },
      {
        city: 'Market Harborough',
        primary_balloons: [],
        country: 'GB',
        key: 362,
        additional_balloons: [
          {
            year_manufactured: '1997',
            reg_num: 'N83036',
            balloon_size_unit: 'cubic feet',
            shape_balloon: 'No',
            photos_url: 'https://registration.balloonfiesta.com/hotair/balloon/image/N83036',
            balloon_name: 'Morning Star',
            logo: 'No',
            balloon_design_desc: 'Red and Orange withYellow Stripe and Red Stars.',
            model: 'AX 7',
            manufacturer: 'Head',
            key: 196,
            balloon_size: '77000',
          },
        ],
        state: 'Northamptonshire',
        common_name: 'Andy Austin',
        events: null,
      },
      {
        city: 'Dexter',
        primary_balloons: [
          {
            year_manufactured: '2015',
            reg_num: 'N590RW',
            balloon_size_unit: 'cubic feet',
            shape_balloon: 'No',
            photos_url: 'https://registration.balloonfiesta.com/hotair/balloon/image/N590RW',
            balloon_name: 'New-but-sold',
            logo: 'No',
            balloon_design_desc: 'Rainbow equator with black and white top and bottom',
            model: 'V-90',
            manufacturer: 'Cameron',
            key: 233,
            balloon_size: '90000',
          },
        ],
        country: 'US',
        key: 226,
        additional_balloons: [],
        state: 'MI',
        common_name: 'Andy Baird',
        events: [
          {
            competition_balloon_id: 233,
            banner_number: '058',
            launch_thur_fri: '',
            launch_shapes: '',
            launch_9day: 'E1',
            launch_balloon_glow: '',
            aloft: 'No',
            launch_twilight_twinkle: '',
            launch_rodeo: '',
            program_balloon_id: 233,
            aloft_school: '',
            launch_night_magic: '',
            us_national_competition: 'No',
          },
        ],
      },
      {
        city: 'Rockhampton',
        primary_balloons: [
          {
            year_manufactured: '2014',
            reg_num: 'G-UINS',
            balloon_size_unit: 'cubic feet',
            shape_balloon: 'Yes',
            photos_url: 'https://registration.balloonfiesta.com/hotair/balloon/image/G-UINS',
            balloon_name: 'Puddles',
            logo: 'No',
            balloon_design_desc: 'Black white penguine',
            model: 'B70',
            manufacturer: 'Ultra Magic',
            key: 699,
            balloon_size: '80000',
          },
        ],
        country: 'GB',
        key: 680,
        additional_balloons: [],
        state: 'Gloucestershire',
        common_name: 'Andy Collett',
        events: [
          {
            competition_balloon_id: null,
            banner_number: '423',
            launch_thur_fri: 'M2',
            launch_shapes: 'N1',
            launch_9day: '',
            launch_balloon_glow: '',
            aloft: 'No',
            launch_twilight_twinkle: 'M2',
            launch_rodeo: 'M1',
            program_balloon_id: 699,
            aloft_school: '',
            launch_night_magic: '',
            us_national_competition: 'No',
          },
        ],
      },
      {
        city: 'El Paso',
        primary_balloons: [
          {
            year_manufactured: '1998',
            reg_num: 'N5303H',
            balloon_size_unit: 'cubic feet',
            shape_balloon: 'No',
            photos_url: 'https://registration.balloonfiesta.com/hotair/balloon/image/N5303H',
            balloon_name: 'HubbaBubba',
            logo: 'No',
            balloon_design_desc: 'yellow,pink,purple,blue, center 5 panels yellow,blue,purple,pink,yellow',
            model: '0-105',
            manufacturer: 'Cameron',
            key: 20,
            balloon_size: '105000',
          },
        ],
        country: 'US',
        key: 8,
        additional_balloons: [],
        state: 'TX',
        common_name: 'Andy Waner',
        events: [
          {
            competition_balloon_id: 20,
            banner_number: '065',
            launch_thur_fri: '',
            launch_shapes: '',
            launch_9day: 'G5',
            launch_balloon_glow: '',
            aloft: 'Yes',
            launch_twilight_twinkle: '',
            launch_rodeo: '',
            program_balloon_id: 20,
            aloft_school: 'Alice King Community School',
            launch_night_magic: '',
            us_national_competition: 'No',
          },
        ],
      },
      {
        city: 'Victorville',
        primary_balloons: [
          {
            year_manufactured: '1989',
            reg_num: 'N64914',
            balloon_size_unit: 'cubic feet',
            shape_balloon: 'No',
            photos_url: 'https://registration.balloonfiesta.com/hotair/balloon/image/N64914',
            balloon_name: 'Outlander',
            logo: 'No',
            balloon_design_desc: 'Black, purple, orange with yellow alien heads and silver diamonds',
            model: 'S60A',
            manufacturer: 'Aerostar',
            key: 155,
            balloon_size: '105000',
          },
        ],
        country: 'US',
        key: 159,
        additional_balloons: [],
        state: 'CA',
        common_name: 'Angela Murphy',
        events: [
          {
            competition_balloon_id: 155,
            banner_number: '147',
            launch_thur_fri: '',
            launch_shapes: '',
            launch_9day: 'C4',
            launch_balloon_glow: 'C4',
            aloft: 'Yes',
            launch_twilight_twinkle: 'C4',
            launch_rodeo: '',
            program_balloon_id: 155,
            aloft_school: 'Ernie Stapleton',
            launch_night_magic: 'C3',
            us_national_competition: 'No',
          },
        ],
      },
      {
        city: 'Tijeras',
        primary_balloons: [
          {
            year_manufactured: '1997',
            reg_num: 'N9038M',
            balloon_size_unit: 'cubic feet',
            shape_balloon: 'No',
            photos_url: 'https://registration.balloonfiesta.com/hotair/balloon/image/N9038M',
            balloon_name: 'Howes Angels II',
            logo: 'No',
            balloon_design_desc: 'Blue with green, yellow and red spray on 2 sides of envelope, black top cap and skirt',
            model: 'S53A',
            manufacturer: 'Aerostar',
            key: 566,
            balloon_size: '69500',
          },
        ],
        country: 'US',
        key: 548,
        additional_balloons: [],
        state: 'NM',
        common_name: 'Angie Howes',
        events: [
          {
            competition_balloon_id: null,
            banner_number: '521',
            launch_thur_fri: '',
            launch_shapes: '',
            launch_9day: 'K11',
            launch_balloon_glow: '',
            aloft: 'Yes',
            launch_twilight_twinkle: '',
            launch_rodeo: 'K10',
            program_balloon_id: 566,
            aloft_school: 'A. Montoya/Roosevelt MS',
            launch_night_magic: '',
            us_national_competition: 'No',
          },
        ],
      },
      {
        city: 'Lorne',
        primary_balloons: [
          {
            year_manufactured: '2008',
            reg_num: 'VH-XUP',
            balloon_size_unit: 'cubic feet',
            shape_balloon: 'No',
            photos_url: 'https://registration.balloonfiesta.com/hotair/balloon/image/VH-XUP',
            balloon_name: 'UP',
            logo: 'No',
            balloon_design_desc: 'Blue and yellow arrows.',
            model: 'GUS69',
            manufacturer: 'Home Built',
            key: 119,
            balloon_size: '69000',
          },
        ],
        country: 'AU',
        key: 125,
        additional_balloons: [],
        state: 'VIC',
        common_name: 'Angus Peart',
        events: [
          {
            competition_balloon_id: 119,
            banner_number: '208',
            launch_thur_fri: '',
            launch_shapes: '',
            launch_9day: 'P7',
            launch_balloon_glow: 'P5',
            aloft: 'No',
            launch_twilight_twinkle: 'P5',
            launch_rodeo: '',
            program_balloon_id: 119,
            aloft_school: '',
            launch_night_magic: 'P5',
            us_national_competition: 'No',
          },
        ],
      },
      {
        city: 'Saint-Bruno',
        primary_balloons: [
          {
            year_manufactured: '2006',
            reg_num: 'C-GGTD',
            balloon_size_unit: 'cubic feet',
            shape_balloon: 'No',
            photos_url: 'https://registration.balloonfiesta.com/hotair/balloon/image/C-GGTD',
            balloon_name: 'Delta',
            logo: 'No',
            balloon_design_desc: 'Yellow, red and blue',
            model: 'AX8',
            manufacturer: 'Cameron',
            key: 208,
            balloon_size: '105000',
          },
          {
            year_manufactured: '1976',
            reg_num: 'N9023A',
            balloon_size_unit: 'cubic feet',
            shape_balloon: 'No',
            photos_url: 'https://registration.balloonfiesta.com/hotair/balloon/image/N9023A',
            balloon_name: 'Sunrise Angel',
            logo: 'No',
            balloon_design_desc: 'Yellow w/black white red rectangles around equator in a chevron pattern.',
            model: 'A55',
            manufacturer: 'Adams',
            key: 519,
            balloon_size: '75000',
          },
        ],
        country: 'CA',
        key: 51,
        additional_balloons: [
          {
            year_manufactured: '2005',
            reg_num: 'C-GGTW',
            balloon_size_unit: 'cubic feet',
            shape_balloon: 'No',
            photos_url: 'https://registration.balloonfiesta.com/hotair/balloon/image/C-GGTW',
            balloon_name: 'Wisky',
            logo: 'No',
            balloon_design_desc: 'mainly red',
            model: 'Z-105',
            manufacturer: 'Cameron',
            key: 139,
            balloon_size: '105000',
          },
          {
            year_manufactured: '2010',
            reg_num: 'C-GHBV',
            balloon_size_unit: 'cubic feet',
            shape_balloon: 'No',
            photos_url: 'https://registration.balloonfiesta.com/hotair/balloon/image/C-GHBV',
            balloon_name: 'LES LIBELLULES',
            logo: 'No',
            balloon_design_desc: 'WHITE WITH TOP BLUE AND DRAGONFLY IN THE WHITE.',
            model: 'AX-8-105',
            manufacturer: 'Fantasy',
            key: 152,
            balloon_size: '105000',
          },
          {
            year_manufactured: '2000',
            reg_num: 'C-GIFW',
            balloon_size_unit: 'cubic feet',
            shape_balloon: 'No',
            photos_url: 'https://registration.balloonfiesta.com/hotair/balloon/image/C-GIFW',
            balloon_name: 'UN SOURIRE DU CIEL II',
            logo: 'No',
            balloon_design_desc: 'YELLOW IN CENTER ORANGE, RED AND BLU ABOVE AND BELOW',
            model: 'AX-8-105',
            manufacturer: 'Fantasy',
            key: 197,
            balloon_size: '105000',
          },
        ],
        state: 'Québec',
        common_name: 'Annie Tessier',
        events: [
          {
            competition_balloon_id: null,
            banner_number: '361',
            launch_thur_fri: '',
            launch_shapes: '',
            launch_9day: 'S8',
            launch_balloon_glow: 'U5',
            aloft: 'No',
            launch_twilight_twinkle: 'U4',
            launch_rodeo: 'S8',
            program_balloon_id: 208,
            aloft_school: '',
            launch_night_magic: 'T3',
            us_national_competition: 'No',
          },
        ],
      },
      {
        city: 'Houston',
        primary_balloons: [
          {
            year_manufactured: '2001',
            reg_num: 'N4503X',
            balloon_size_unit: 'cubic feet',
            shape_balloon: 'No',
            photos_url: 'https://registration.balloonfiesta.com/hotair/balloon/image/N4503X',
            balloon_name: 'Almost There',
            logo: 'No',
            balloon_design_desc: 'Yellow with pink and teal south west print',
            model: 'Z',
            manufacturer: 'Cameron',
            key: 27,
            balloon_size: '65000',
          },
        ],
        country: 'US',
        key: 18,
        additional_balloons: [],
        state: 'TX',
        common_name: 'Anthony Haynes',
        events: [
          {
            competition_balloon_id: 27,
            banner_number: '011',
            launch_thur_fri: '',
            launch_shapes: '',
            launch_9day: 'D2',
            launch_balloon_glow: 'D2',
            aloft: 'No',
            launch_twilight_twinkle: '',
            launch_rodeo: '',
            program_balloon_id: 27,
            aloft_school: '',
            launch_night_magic: '',
            us_national_competition: 'No',
          },
        ],
      },
      {
        city: 'Ledegem',
        primary_balloons: [
          {
            year_manufactured: '1994',
            reg_num: 'N9182D',
            balloon_size_unit: 'cubic feet',
            shape_balloon: 'No',
            photos_url: 'https://registration.balloonfiesta.com/hotair/balloon/image/N9182D',
            balloon_name: 'Little Bit of Heaven',
            logo: 'No',
            balloon_design_desc: 'Standard balloon\r\nrainbow on top\r\nblack on the bottom',
            model: 'RXS-8',
            manufacturer: 'Aerostar',
            key: 584,
            balloon_size: '105000',
          },
        ],
        country: 'BE',
        key: 509,
        additional_balloons: [],
        state: 'West Vlaanderen',
        common_name: 'Arne Lips',
        events: [
          {
            competition_balloon_id: 584,
            banner_number: '217',
            launch_thur_fri: '',
            launch_shapes: '',
            launch_9day: 'L10',
            launch_balloon_glow: '',
            aloft: 'No',
            launch_twilight_twinkle: '',
            launch_rodeo: '',
            program_balloon_id: 584,
            aloft_school: '',
            launch_night_magic: '',
            us_national_competition: 'No',
          },
        ],
      },
      {
        city: 'Albuquerque',
        primary_balloons: [
          {
            year_manufactured: '1991',
            reg_num: 'N9074S',
            balloon_size_unit: 'cubic feet',
            shape_balloon: 'No',
            photos_url: 'https://registration.balloonfiesta.com/hotair/balloon/image/N9074S',
            balloon_name: 'Double Flash',
            logo: 'No',
            balloon_design_desc: 'Rainbow',
            model: 'Firefly',
            manufacturer: 'Balloon Works',
            key: 339,
            balloon_size: '77500',
          },
        ],
        country: 'US',
        key: 332,
        additional_balloons: [],
        state: 'NM',
        common_name: 'Art Lites',
        events: [
          {
            competition_balloon_id: 339,
            banner_number: '136',
            launch_thur_fri: '',
            launch_shapes: '',
            launch_9day: 'U3',
            launch_balloon_glow: 'U3',
            aloft: 'No',
            launch_twilight_twinkle: '',
            launch_rodeo: '',
            program_balloon_id: 339,
            aloft_school: '',
            launch_night_magic: '',
            us_national_competition: 'No',
          },
        ],
      },
      {
        city: 'Stonehouse',
        primary_balloons: [
          {
            year_manufactured: '2016',
            reg_num: 'G-LEAT',
            balloon_size_unit: 'cubic feet',
            shape_balloon: 'Yes',
            photos_url: 'https://registration.balloonfiesta.com/hotair/balloon/image/G-LEAT',
            balloon_name: 'Simbaloo',
            logo: 'No',
            balloon_design_desc: 'lion',
            model: 'Cameron B70',
            manufacturer: 'Cameron',
            key: 687,
            balloon_size: '70000',
          },
        ],
        country: 'GB',
        key: 666,
        additional_balloons: [],
        state: 'Gloucestershire',
        common_name: 'Ashley Moore',
        events: [
          {
            competition_balloon_id: null,
            banner_number: '431',
            launch_thur_fri: 'B6',
            launch_shapes: 'M1',
            launch_9day: '',
            launch_balloon_glow: 'M1',
            aloft: 'No',
            launch_twilight_twinkle: 'M1',
            launch_rodeo: 'B3',
            program_balloon_id: 687,
            aloft_school: '',
            launch_night_magic: 'M1',
            us_national_competition: 'No',
          },
        ],
      },
      {
        city: 'Albuquerque',
        primary_balloons: [
          {
            year_manufactured: '2014',
            reg_num: 'N70978',
            balloon_size_unit: 'cubic feet',
            shape_balloon: 'No',
            photos_url: 'https://registration.balloonfiesta.com/hotair/balloon/image/N70978',
            balloon_name: 'Sandia Sunrise II',
            logo: 'No',
            balloon_design_desc: 'blue and yellow vertical strips with red arrows between every other blue/yellow',
            model: 'RX-8',
            manufacturer: 'Home Built',
            key: 469,
            balloon_size: '90000',
          },
        ],
        country: 'US',
        key: 452,
        additional_balloons: [],
        state: 'NM',
        common_name: 'Barbara Fricke',
        events: [
          {
            competition_balloon_id: 469,
            banner_number: '712',
            launch_thur_fri: '',
            launch_shapes: '',
            launch_9day: 'U9',
            launch_balloon_glow: 'U6',
            aloft: 'Yes',
            launch_twilight_twinkle: '',
            launch_rodeo: '',
            program_balloon_id: 469,
            aloft_school: 'Maggie Cordova',
            launch_night_magic: '',
            us_national_competition: 'Yes',
          },
        ],
      },
      {
        city: 'Siler City',
        primary_balloons: [
          {
            year_manufactured: '1997',
            reg_num: 'N83036',
            balloon_size_unit: 'cubic feet',
            shape_balloon: 'No',
            photos_url: 'https://registration.balloonfiesta.com/hotair/balloon/image/N83036',
            balloon_name: 'Morning Star',
            logo: 'No',
            balloon_design_desc: 'Red and Orange withYellow Stripe and Red Stars.',
            model: 'AX 7',
            manufacturer: 'Head',
            key: 196,
            balloon_size: '77000',
          },
        ],
        country: 'US',
        key: 181,
        additional_balloons: [
          {
            year_manufactured: '1996',
            reg_num: 'N3982Y',
            balloon_size_unit: 'cubic feet',
            shape_balloon: 'No',
            photos_url: 'https://registration.balloonfiesta.com/hotair/balloon/image/N3982Y',
            balloon_name: 'Dances with Winds',
            logo: 'No',
            balloon_design_desc: 'yellow, blue, red, orange rainbow',
            model: 'Canon',
            manufacturer: 'Cameron',
            key: 343,
            balloon_size: '90000',
          },
        ],
        state: 'NC',
        common_name: 'Barbara McKinley',
        events: [
          {
            competition_balloon_id: null,
            banner_number: '357',
            launch_thur_fri: '',
            launch_shapes: '',
            launch_9day: 'R11',
            launch_balloon_glow: '',
            aloft: 'No',
            launch_twilight_twinkle: 'M6',
            launch_rodeo: 'R11',
            program_balloon_id: 196,
            aloft_school: '',
            launch_night_magic: '',
            us_national_competition: 'No',
          },
        ],
      },
      {
        city: 'Albuquerque',
        primary_balloons: [
          {
            year_manufactured: '2006',
            reg_num: 'N218CB',
            balloon_size_unit: 'cubic feet',
            shape_balloon: 'No',
            photos_url: 'https://registration.balloonfiesta.com/hotair/balloon/image/N218CB',
            balloon_name: 'COOL BEANS!!',
            logo: 'No',
            balloon_design_desc: 'six colors spiral (red, royal blue, yellow, purple, green, powder blue) with 6 Bean figures',
            model: '105A',
            manufacturer: 'Lindstrand',
            key: 305,
            balloon_size: '105000',
          },
        ],
        country: 'US',
        key: 292,
        additional_balloons: [],
        state: 'NM',
        common_name: 'Barney Watson',
        events: [
          {
            competition_balloon_id: null,
            banner_number: '408',
            launch_thur_fri: '',
            launch_shapes: '',
            launch_9day: 'B8',
            launch_balloon_glow: '',
            aloft: 'Yes',
            launch_twilight_twinkle: '',
            launch_rodeo: 'B8',
            program_balloon_id: 305,
            aloft_school: 'St. Charles Borromeo School',
            launch_night_magic: '',
            us_national_competition: 'No',
          },
        ],
      },
      {
        city: 'Lubbock',
        primary_balloons: [
          {
            year_manufactured: '2002',
            reg_num: 'N322PC',
            balloon_size_unit: 'cubic feet',
            shape_balloon: 'Yes',
            photos_url: 'https://registration.balloonfiesta.com/hotair/balloon/image/N322PC',
            balloon_name: 'In The Buff',
            logo: 'Yes',
            balloon_design_desc: 'Blue Envelope with two buffalo heads',
            model: 'S57S',
            manufacturer: 'Aerostar',
            key: 237,
            balloon_size: '90000',
          },
        ],
        country: 'US',
        key: 110,
        additional_balloons: [],
        state: 'TX',
        common_name: 'Barry Ballinger',
        events: [
          {
            competition_balloon_id: null,
            banner_number: '374',
            launch_thur_fri: 'H1',
            launch_shapes: 'F6',
            launch_9day: '',
            launch_balloon_glow: 'F6',
            aloft: 'No',
            launch_twilight_twinkle: '',
            launch_rodeo: 'H1',
            program_balloon_id: 237,
            aloft_school: '',
            launch_night_magic: 'F5',
            us_national_competition: 'No',
          },
        ],
      },
      {
        city: 'Laren',
        primary_balloons: [
          {
            year_manufactured: '2002',
            reg_num: 'PH-DEX',
            balloon_size_unit: 'cubic feet',
            shape_balloon: 'Yes',
            photos_url: 'https://registration.balloonfiesta.com/hotair/balloon/image/PH-DEX',
            balloon_name: 'Dexter',
            logo: 'No',
            balloon_design_desc: 'Blue/red Flame',
            model: 'Flame-95',
            manufacturer: 'Cameron',
            key: 517,
            balloon_size: '95000',
          },
        ],
        country: 'NL',
        key: 497,
        additional_balloons: [],
        state: 'Gelderland',
        common_name: 'Bas Spierenburg',
        events: [
          {
            competition_balloon_id: null,
            banner_number: '488',
            launch_thur_fri: 'G4',
            launch_shapes: 'J8',
            launch_9day: '',
            launch_balloon_glow: 'H2',
            aloft: 'No',
            launch_twilight_twinkle: 'H2',
            launch_rodeo: 'G3',
            program_balloon_id: 517,
            aloft_school: '',
            launch_night_magic: 'H2',
            us_national_competition: 'No',
          },
        ],
      },
      {
        city: 'Louisburg',
        primary_balloons: [
          {
            year_manufactured: '2009',
            reg_num: 'N509BP',
            balloon_size_unit: 'cubic feet',
            shape_balloon: 'No',
            photos_url: 'https://registration.balloonfiesta.com/hotair/balloon/image/N509BP',
            balloon_name: 'Twisted Sister',
            logo: 'No',
            balloon_design_desc: 'Multi-colored spiral with large white center',
            model: 'Z105',
            manufacturer: 'Cameron',
            key: 468,
            balloon_size: '105000',
          },
        ],
        country: 'US',
        key: 451,
        additional_balloons: [],
        state: 'KS',
        common_name: 'Becky Petrehn',
        events: [
          {
            competition_balloon_id: 468,
            banner_number: '089',
            launch_thur_fri: '',
            launch_shapes: '',
            launch_9day: 'E2',
            launch_balloon_glow: '',
            aloft: 'No',
            launch_twilight_twinkle: '',
            launch_rodeo: '',
            program_balloon_id: 468,
            aloft_school: '',
            launch_night_magic: '',
            us_national_competition: 'No',
          },
        ],
      },
      {
        city: 'ANNONAY',
        primary_balloons: [
          {
            year_manufactured: '2014',
            reg_num: 'FHBFN',
            balloon_size_unit: 'cubic meters',
            shape_balloon: 'No',
            photos_url: 'https://registration.balloonfiesta.com/hotair/balloon/image/FHBFN',
            balloon_name: 'Dawn Chaser',
            logo: 'Yes',
            balloon_design_desc: 'dark blue with a swallow and written ballons chaize on it',
            model: 'DC2200 F16',
            manufacturer: 'Ballons Chaize',
            key: 639,
            balloon_size: '2200',
          },
        ],
        country: 'FR',
        key: 622,
        additional_balloons: [],
        state: 'ardeche',
        common_name: 'Ben Cleyet-Marrel',
        events: [
          {
            competition_balloon_id: null,
            banner_number: '542',
            launch_thur_fri: '',
            launch_shapes: '',
            launch_9day: 'R9',
            launch_balloon_glow: 'R7',
            aloft: 'No',
            launch_twilight_twinkle: '',
            launch_rodeo: 'R10',
            program_balloon_id: 639,
            aloft_school: '',
            launch_night_magic: '',
            us_national_competition: 'No',
          },
        ],
      },
      {
        city: 'Pensacola',
        primary_balloons: [
          {
            year_manufactured: '1987',
            reg_num: 'N65652',
            balloon_size_unit: 'cubic feet',
            shape_balloon: 'No',
            photos_url: 'https://registration.balloonfiesta.com/hotair/balloon/image/N65652',
            balloon_name: 'Seasons',
            logo: 'No',
            balloon_design_desc: 'Purple with Yellow Pennants. Seasonal Artwork around the equator.',
            model: 'S-57A',
            manufacturer: 'Aerostar',
            key: 190,
            balloon_size: '90000',
          },
        ],
        country: 'US',
        key: 186,
        additional_balloons: [],
        state: 'FL',
        common_name: 'Ben Drennan',
        events: [
          {
            competition_balloon_id: null,
            banner_number: '350',
            launch_thur_fri: '',
            launch_shapes: '',
            launch_9day: 'H2',
            launch_balloon_glow: 'H4',
            aloft: 'Yes',
            launch_twilight_twinkle: 'H4',
            launch_rodeo: 'F5',
            program_balloon_id: 190,
            aloft_school: 'Duranes',
            launch_night_magic: 'H4',
            us_national_competition: 'No',
          },
        ],
      },
      {
        city: 'Columbia',
        primary_balloons: [
          {
            year_manufactured: '1993',
            reg_num: 'N768TC',
            balloon_size_unit: 'cubic feet',
            shape_balloon: 'No',
            photos_url: 'https://registration.balloonfiesta.com/hotair/balloon/image/N768TC',
            balloon_name: 'Flamingo',
            logo: 'No',
            balloon_design_desc: 'Pink with stair step navy blue and yellow',
            model: '77A',
            manufacturer: 'Thunder&Colt',
            key: 32,
            balloon_size: '77000',
          },
          {
            year_manufactured: '2016',
            reg_num: 'N560BH',
            balloon_size_unit: 'cubic feet',
            shape_balloon: 'No',
            photos_url: 'https://registration.balloonfiesta.com/hotair/balloon/image/N560BH',
            balloon_name: 'Buzz',
            logo: 'No',
            balloon_design_desc: 'Black with checkered yellow',
            model: 'B56R',
            manufacturer: 'Home Built',
            key: 758,
            balloon_size: '56000',
          },
        ],
        country: 'US',
        key: 61,
        additional_balloons: [],
        state: 'MO',
        common_name: 'Ben Humphreys',
        events: [
          {
            competition_balloon_id: 758,
            banner_number: '020',
            launch_thur_fri: '',
            launch_shapes: '',
            launch_9day: 'W5',
            launch_balloon_glow: 'W5',
            aloft: 'No',
            launch_twilight_twinkle: 'W3',
            launch_rodeo: '',
            program_balloon_id: 32,
            aloft_school: '',
            launch_night_magic: '',
            us_national_competition: 'No',
          },
        ],
      },
      {
        city: 'Kamenz',
        primary_balloons: [],
        country: 'GH',
        key: 574,
        additional_balloons: [
          {
            year_manufactured: '2008',
            reg_num: 'D-OZZZ',
            balloon_size_unit: 'cubic meters',
            shape_balloon: 'Yes',
            photos_url: 'https://registration.balloonfiesta.com/hotair/balloon/image/D-OZZZ',
            balloon_name: 'SkyHeart',
            logo: 'Yes',
            balloon_design_desc: 'red Heart',
            model: 'Schroeder Fireballoons',
            manufacturer: 'Schroeder',
            key: 568,
            balloon_size: '3000',
          },
        ],
        state: 'Saxony',
        common_name: 'Benjamin Bannert',
        events: null,
      },
      {
        city: 'Court St Etienne',
        primary_balloons: [
          {
            year_manufactured: '2007',
            reg_num: 'OO-BQZ',
            balloon_size_unit: 'cubic feet',
            shape_balloon: 'Yes',
            photos_url: 'https://registration.balloonfiesta.com/hotair/balloon/image/OO-BQZ',
            balloon_name: 'Darth Vader Balloon',
            logo: 'No',
            balloon_design_desc: 'helmet of the best vilain heroes from movies',
            model: 'ss 105 head one',
            manufacturer: 'Cameron',
            key: 217,
            balloon_size: '105000',
          },
        ],
        country: 'BE',
        key: 212,
        additional_balloons: [],
        state: 'na',
        common_name: 'Benoit Lambert',
        events: [
          {
            competition_balloon_id: null,
            banner_number: '369',
            launch_thur_fri: 'J2',
            launch_shapes: 'Q1',
            launch_9day: '',
            launch_balloon_glow: '',
            aloft: 'No',
            launch_twilight_twinkle: '',
            launch_rodeo: 'J2',
            program_balloon_id: 217,
            aloft_school: '',
            launch_night_magic: '',
            us_national_competition: 'No',
          },
        ],
      },
      {
        city: 'El paso',
        primary_balloons: [
          {
            year_manufactured: '2001',
            reg_num: 'N369CW',
            balloon_size_unit: 'cubic feet',
            shape_balloon: 'No',
            photos_url: 'https://registration.balloonfiesta.com/hotair/balloon/image/N369CW',
            balloon_name: 'EMINENCE',
            logo: 'No',
            balloon_design_desc: 'Yellow,blue ,red ,checkers',
            model: 'A-69',
            manufacturer: 'Lindstrand',
            key: 240,
            balloon_size: '69000',
          },
        ],
        country: 'US',
        key: 231,
        additional_balloons: [],
        state: 'TX',
        common_name: 'Bernard F Smatana',
        events: [
          {
            competition_balloon_id: 240,
            banner_number: '213',
            launch_thur_fri: '',
            launch_shapes: '',
            launch_9day: 'L8',
            launch_balloon_glow: '',
            aloft: 'Yes',
            launch_twilight_twinkle: '',
            launch_rodeo: '',
            program_balloon_id: 240,
            aloft_school: 'John Baker',
            launch_night_magic: '',
            us_national_competition: 'No',
          },
        ],
      },
      {
        city: 'Albuquerque',
        primary_balloons: [
          {
            year_manufactured: '2014',
            reg_num: 'N990WF',
            balloon_size_unit: 'cubic feet',
            shape_balloon: 'Yes',
            photos_url: 'https://registration.balloonfiesta.com/hotair/balloon/image/N990WF',
            balloon_name: "Cent'r Stage",
            logo: 'Yes',
            balloon_design_desc: 'red stagecoach with Wells Fargo written at top',
            model: 'Stagecoach 110',
            manufacturer: 'Cameron',
            key: 407,
            balloon_size: '160000',
          },
        ],
        country: 'US',
        key: 394,
        additional_balloons: [
          {
            year_manufactured: '2008',
            reg_num: 'N994WF',
            balloon_size_unit: 'cubic feet',
            shape_balloon: 'No',
            photos_url: 'https://registration.balloonfiesta.com/hotair/balloon/image/N994WF',
            balloon_name: 'Wells Fargo I',
            logo: 'Yes',
            balloon_design_desc: 'Wells Fargo Logo',
            model: 'Z105',
            manufacturer: 'Cameron',
            key: 432,
            balloon_size: '105000',
          },
          {
            year_manufactured: '2009',
            reg_num: 'N993WF',
            balloon_size_unit: 'cubic feet',
            shape_balloon: 'No',
            photos_url: 'https://registration.balloonfiesta.com/hotair/balloon/image/N993WF',
            balloon_name: 'Wells Fargo II',
            logo: 'Yes',
            balloon_design_desc: 'Red, white, maroon with Wells Fargo logo and stagecoach artwork.',
            model: 'Z-105',
            manufacturer: 'Cameron',
            key: 494,
            balloon_size: '105000',
          },
        ],
        state: 'NM',
        common_name: 'Beth Wright-Smith',
        events: [
          {
            competition_balloon_id: null,
            banner_number: '496',
            launch_thur_fri: 'J1',
            launch_shapes: 'J1',
            launch_9day: '',
            launch_balloon_glow: 'J1',
            aloft: 'No',
            launch_twilight_twinkle: 'J1',
            launch_rodeo: 'J1',
            program_balloon_id: 407,
            aloft_school: '',
            launch_night_magic: 'J1',
            us_national_competition: 'No',
          },
        ],
      },
      {
        city: 'Goodyear',
        primary_balloons: [
          {
            year_manufactured: '2009',
            reg_num: 'N379LB',
            balloon_size_unit: 'cubic feet',
            shape_balloon: 'No',
            photos_url: 'https://registration.balloonfiesta.com/hotair/balloon/image/N379LB',
            balloon_name: 'Band of Gold',
            logo: 'No',
            balloon_design_desc: 'Black, Red, Blue, Green alternating squares top & bottom third.  Solid yellow middle third.',
            model: '90A',
            manufacturer: 'Lindstrand',
            key: 552,
            balloon_size: '90000',
          },
        ],
        country: 'US',
        key: 532,
        additional_balloons: [],
        state: 'AZ',
        common_name: 'Bill Armstrong',
        events: [
          {
            competition_balloon_id: 552,
            banner_number: '228',
            launch_thur_fri: '',
            launch_shapes: '',
            launch_9day: 'P5',
            launch_balloon_glow: 'P7',
            aloft: 'No',
            launch_twilight_twinkle: '',
            launch_rodeo: '',
            program_balloon_id: 552,
            aloft_school: '',
            launch_night_magic: '',
            us_national_competition: 'No',
          },
        ],
      },
      {
        city: 'Tyler',
        primary_balloons: [
          {
            year_manufactured: '2016',
            reg_num: 'BIMBO BEAR',
            balloon_size_unit: 'cubic feet',
            shape_balloon: 'Yes',
            photos_url: 'https://registration.balloonfiesta.com/hotair/balloon/image/BIMBO BEAR',
            balloon_name: 'Osito Bimbo',
            logo: 'Yes',
            balloon_design_desc: 'White bear head with hat',
            model: 'Bear 120',
            manufacturer: 'Cameron',
            key: 742,
            balloon_size: '120000',
          },
        ],
        country: 'US',
        key: 729,
        additional_balloons: [],
        state: 'TX',
        common_name: 'Bill Baker',
        events: [
          {
            competition_balloon_id: null,
            banner_number: '424',
            launch_thur_fri: 'F2',
            launch_shapes: 'N1',
            launch_9day: '',
            launch_balloon_glow: 'N1',
            aloft: 'No',
            launch_twilight_twinkle: 'N1',
            launch_rodeo: 'F1',
            program_balloon_id: 742,
            aloft_school: '',
            launch_night_magic: 'N1',
            us_national_competition: 'No',
          },
        ],
      },
      {
        city: 'Frisco',
        primary_balloons: [
          {
            year_manufactured: '2016',
            reg_num: 'N972PT',
            balloon_size_unit: 'cubic feet',
            shape_balloon: 'No',
            photos_url: 'https://registration.balloonfiesta.com/hotair/balloon/image/N972PT',
            balloon_name: 'Excellence',
            logo: 'Yes',
            balloon_design_desc: 'Red, white, blue And black spiral',
            model: 'ZL-70',
            manufacturer: 'Cameron',
            key: 57,
            balloon_size: '70000',
          },
        ],
        country: 'US',
        key: 74,
        additional_balloons: [],
        state: 'TX',
        common_name: 'Bill Broker',
        events: [
          {
            competition_balloon_id: 57,
            banner_number: '018',
            launch_thur_fri: '',
            launch_shapes: '',
            launch_9day: 'E1',
            launch_balloon_glow: 'E1',
            aloft: 'No',
            launch_twilight_twinkle: '',
            launch_rodeo: '',
            program_balloon_id: 57,
            aloft_school: '',
            launch_night_magic: '',
            us_national_competition: 'No',
          },
        ],
      },
      {
        city: 'Longview',
        primary_balloons: [
          {
            year_manufactured: '2007',
            reg_num: 'N169LB',
            balloon_size_unit: 'cubic feet',
            shape_balloon: 'No',
            photos_url: 'https://registration.balloonfiesta.com/hotair/balloon/image/N169LB',
            balloon_name: 'Blue Diamond',
            logo: 'No',
            balloon_design_desc: 'Green,Black,Blue',
            model: '60X',
            manufacturer: 'Lindstrand',
            key: 330,
            balloon_size: '60000',
          },
        ],
        country: 'US',
        key: 324,
        additional_balloons: [],
        state: 'TX',
        common_name: 'Bill Bussey',
        events: [
          {
            competition_balloon_id: 330,
            banner_number: '023',
            launch_thur_fri: '',
            launch_shapes: '',
            launch_9day: 'F7',
            launch_balloon_glow: '',
            aloft: 'No',
            launch_twilight_twinkle: '',
            launch_rodeo: '',
            program_balloon_id: 330,
            aloft_school: '',
            launch_night_magic: '',
            us_national_competition: 'No',
          },
        ],
      },
      {
        city: 'Corrales',
        primary_balloons: [],
        country: 'US',
        key: 748,
        additional_balloons: [
          {
            year_manufactured: '1995',
            reg_num: 'N7145C',
            balloon_size_unit: 'cubic feet',
            shape_balloon: 'No',
            photos_url: 'https://registration.balloonfiesta.com/hotair/balloon/image/N7145C',
            balloon_name: '2nd Wind',
            logo: 'No',
            balloon_design_desc: 'Black pink and teal wedding cake',
            model: 's53',
            manufacturer: 'Aerostar',
            key: 206,
            balloon_size: '69000',
          },
        ],
        state: 'NM',
        common_name: 'Bill Dickey',
        events: null,
      },
      {
        city: 'Los Lunas',
        primary_balloons: [
          {
            year_manufactured: '1986',
            reg_num: 'N40229',
            balloon_size_unit: 'cubic feet',
            shape_balloon: 'No',
            photos_url: 'https://registration.balloonfiesta.com/hotair/balloon/image/N40229',
            balloon_name: 'Angel of the Morning',
            logo: 'No',
            balloon_design_desc: 'Black with Starburst',
            model: 'A55S',
            manufacturer: 'Adams',
            key: 518,
            balloon_size: '83000',
          },
          {
            year_manufactured: '1976',
            reg_num: 'N9023A',
            balloon_size_unit: 'cubic feet',
            shape_balloon: 'No',
            photos_url: 'https://registration.balloonfiesta.com/hotair/balloon/image/N9023A',
            balloon_name: 'Sunrise Angel',
            logo: 'No',
            balloon_design_desc: 'Yellow w/black white red rectangles around equator in a chevron pattern.',
            model: 'A55',
            manufacturer: 'Adams',
            key: 519,
            balloon_size: '75000',
          },
          {
            year_manufactured: '1982',
            reg_num: 'N1059B',
            balloon_size_unit: 'cubic feet',
            shape_balloon: 'No',
            photos_url: 'https://registration.balloonfiesta.com/hotair/balloon/image/N1059B',
            balloon_name: 'Heavenly Angel',
            logo: 'No',
            balloon_design_desc: 'Vertical Rainbow with white stars',
            model: 'A55',
            manufacturer: 'Adams',
            key: 520,
            balloon_size: '75000',
          },
        ],
        country: 'US',
        key: 498,
        additional_balloons: [],
        state: 'NM',
        common_name: 'Bill Dimmitt',
        events: [
          {
            competition_balloon_id: null,
            banner_number: '485',
            launch_thur_fri: '',
            launch_shapes: '',
            launch_9day: 'G9',
            launch_balloon_glow: 'G7',
            aloft: 'Yes',
            launch_twilight_twinkle: 'G6',
            launch_rodeo: 'G9',
            program_balloon_id: 518,
            aloft_school: 'Kit Carson ',
            launch_night_magic: 'G5',
            us_national_competition: 'No',
          },
        ],
      },
      {
        city: 'Maricopa',
        primary_balloons: [
          {
            year_manufactured: '2004',
            reg_num: 'N39929',
            balloon_size_unit: 'cubic feet',
            shape_balloon: 'No',
            photos_url: 'https://registration.balloonfiesta.com/hotair/balloon/image/N39929',
            balloon_name: 'Flamboyant',
            logo: 'No',
            balloon_design_desc: 'Red with neon colors',
            model: 'Cameron',
            manufacturer: 'Cameron',
            key: 780,
            balloon_size: '90000',
          },
        ],
        country: 'US',
        key: 595,
        additional_balloons: [
          {
            year_manufactured: '1985',
            reg_num: 'N60438',
            balloon_size_unit: 'cubic feet',
            shape_balloon: 'No',
            photos_url: 'https://registration.balloonfiesta.com/hotair/balloon/image/N60438',
            balloon_name: 'Skittles',
            logo: 'No',
            balloon_design_desc: 'red/green/yellow/orange/blue',
            model: 'V77',
            manufacturer: 'Cameron',
            key: 732,
            balloon_size: '77000',
          },
        ],
        state: 'AZ',
        common_name: 'Bill Glen',
        events: [
          {
            competition_balloon_id: 780,
            banner_number: '171',
            launch_thur_fri: '',
            launch_shapes: '',
            launch_9day: 'F10',
            launch_balloon_glow: '',
            aloft: 'No',
            launch_twilight_twinkle: '',
            launch_rodeo: '',
            program_balloon_id: 780,
            aloft_school: '',
            launch_night_magic: '',
            us_national_competition: 'No',
          },
        ],
      },
      {
        city: 'Alturas',
        primary_balloons: [
          {
            year_manufactured: '1996',
            reg_num: 'N71630',
            balloon_size_unit: 'cubic feet',
            shape_balloon: 'No',
            photos_url: 'https://registration.balloonfiesta.com/hotair/balloon/image/N71630',
            balloon_name: 'Butterfly',
            logo: 'No',
            balloon_design_desc: 'yellow',
            model: 'RX8',
            manufacturer: 'Aerostar',
            key: 512,
            balloon_size: '90000',
          },
        ],
        country: 'US',
        key: 493,
        additional_balloons: [],
        state: 'CA',
        common_name: 'Bill Goodman',
        events: [
          {
            competition_balloon_id: null,
            banner_number: '486',
            launch_thur_fri: '',
            launch_shapes: '',
            launch_9day: 'Q7',
            launch_balloon_glow: 'Q6',
            aloft: 'No',
            launch_twilight_twinkle: '',
            launch_rodeo: 'Q7',
            program_balloon_id: 512,
            aloft_school: '',
            launch_night_magic: '',
            us_national_competition: 'No',
          },
        ],
      },
      {
        city: 'Gallup',
        primary_balloons: [
          {
            year_manufactured: '2016',
            reg_num: 'N69523',
            balloon_size_unit: 'cubic feet',
            shape_balloon: 'No',
            photos_url: 'https://registration.balloonfiesta.com/hotair/balloon/image/N69523',
            balloon_name: 'True-Lee New Mexico',
            logo: 'Yes',
            balloon_design_desc: 'Black with multi colored sugar skulls on top and bottom & New Mexico True logo on each side.',
            model: 'Z-120',
            manufacturer: 'Cameron',
            key: 597,
            balloon_size: '120000',
          },
        ],
        country: 'US',
        key: 581,
        additional_balloons: [],
        state: 'NM',
        common_name: 'Bill Lee',
        events: [
          {
            competition_balloon_id: null,
            banner_number: '514',
            launch_thur_fri: '',
            launch_shapes: '',
            launch_9day: 'K2',
            launch_balloon_glow: 'K2',
            aloft: 'No',
            launch_twilight_twinkle: '',
            launch_rodeo: 'K4',
            program_balloon_id: 597,
            aloft_school: '',
            launch_night_magic: '',
            us_national_competition: 'No',
          },
        ],
      },
    ],
  };
  componentDidMount() {
    // Ionicons.getImageSource(...switchIconPerPlatform('', 'funnel', 'funnel')).then(filter => {
    //   this.props.navigator.setButtons({
    //     rightButtons: [{ key: 'filter-pilots', icon: filter }],
    //   });
    // });
  }
  promptForLongPress = pilot => {
    const { navigator } = this.props;
    const { common_name, primary_balloons } = pilot;
    Alert.alert(
      "Require's Attention",
      `Would you like to view the First Primary balloon for "${common_name}"`,
      [
        {
          text: 'Cancel',
          onPress: () => {},
          style: 'cancel',
        },
        {
          text: 'OK',
          onPress: () =>
            navigator.push({
              screen: 'bf.Balloon',
              passProps: {
                balloon: primary_balloons,
              },
            }),
        },
      ]
    );
  };
  renderRow = pilot => {
    const { navigator } = this.props;
    return (
      <PilotItem
        pilot={pilot}
        onPressAction={() =>
          navigator.push({
            screen: 'bf.Pilot',
            title: pilot.common_name,
            passProps: { pilot: pilot, isPreview: false },
          })}
        onLongPressAction={() => this.promptForLongPress(pilot)}
      />
    );
  };
  renderSeperator() {
    return <View style={{ height: 5 }} />;
  }
  shouldItemUpdate(prev, next) {
    return prev.item.common_name !== next.item.common_name;
  }
  render() {
    return (
      <View style={styles.container}>
        <FlatList
          style={{ flex: 1 }}
          data={this.state.items}
          legacyImplementation={false}
          renderItem={({ item }) => this.renderRow(item)}
          viewabilityConfig={VIEWABILITY_CONFIG}
          ItemSeparatorComponent={() => this.renderSeperator()}
        />
      </View>
    );
  }
}
export default Pilots;
