# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FiestaApp2017' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for FiestaApp2017
  pod 'RNMobileCenter', '~> 0.3.0'
  pod 'MobileCenter', '~> 0.5.0'

  

  target 'FiestaApp2017Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'FiestaApp2017-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for FiestaApp2017-tvOS

  target 'FiestaApp2017-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
